<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/datepicker.min.js"></script>
    <title>Create Task</title>

</head>

<body>
    <!-- boton return-->

    <h1 class="flex justify-center pt-0 mt-14 pb-4 items-center mb-4 text-4xl font-extrabold 
leading-none tracking-tight text-gray-800 md:text-5xl lg:text-6xl dark:text-white">New Task</h1>



    <div class="w-full md:w-3/5 md:max-w-full mx-auto relative">
        <div class="p-12 border bg-red-200 sm:rounded-md">
            <div class="m-2 flex flex-wrap flex-grow justify-end w-full">
                <div class="absolute top-4 right-4 m-2">
                    <a href="<?php echo WEB_ROOT; ?>"
                        class="inline-block px-4 py-2 font-medium text-white bg-red-300 rounded-md hover:bg-red-200 focus:outline-none focus:shadow-outline-blue active:bg-red-200 transition duration-150 ease-in-out">
                        Cancel <i class="fa-solid fa-xmark"></i>
                    </a>
                </div>
            </div>
            <form action="createTask" name="createTask" id="createTask" method="post">

                <label class="block mb-6">
                    <span class="text-gray-700">Task Description</span>
                    <input type="text" name="description" class="
                    block
                    w-full
                    mt-1
                    p-8
                    pl-5
                    border-gray-300
                    rounded-md
                    shadow-sm
                    focus:border-indigo-300
                    focus:ring
                    focus:ring-indigo-200
                    focus:ring-opacity-50
          " placeholder="Insert task description" required />
                </label>
                <label class="block mb-6">
                    <span class="text-gray-700">Author</span>
                    <input type="text" name="author" class="
                    block
                    w-full
                    mt-1
                    p-5
                    border-gray-300
                    rounded-md
                    shadow-sm
                    focus:border-indigo-300
                    focus:ring
                    focus:ring-indigo-200
                    focus:ring-opacity-50
          " placeholder="Name" required />
                </label>
                <label class="block mb-6">
                    <span class="text-gray-700">Task Status</span>
                    <select text="status" name="status" class="
                    block
                    w-full
                    mt-1
                    p-5
                    border-gray-300
                    rounded-md
                    shadow-sm
                    focus:border-indigo-300
                    focus:ring
                    focus:ring-indigo-200
                    focus:ring-opacity-50
                ">
                        <option value="initialized">Initialized</option>
                        <option value="in process">In process</option>
                        <option value="finalized">Finalized</option>

                    </select>
                </label>
                <label class="block mb-6">
                    <span class="text-gray-700">Completion Deadline</span>

                    <div class="relative max-w-sm">
                        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" fill="currentColor"
                                viewBox="20 20 20 20">
                                <path
                                    d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z" />
                            </svg>
                        </div>

                        <input type="date" min="<?php echo date('Y-m-d'); ?>" name="deadline" class="
                            block
                            w-full
                            mt-1
                            p-5
                            border-gray-300
                            rounded-md
                            shadow-sm
                            focus:border-indigo-300
                            focus:ring
                            focus:ring-indigo-200
                            focus:ring-opacity-50" placeholder="Select date" required>
                    </div>
                </label>
                <div class="mb-6 flex justify-center items-center ">
                    <button type="submit" id="createButton" class="
                    h-20
                    px-20
                    text-white
                    bg-red-400
                    rounded-lg
                    transition-colors
                    duration-150
                    focus:shadow-outline
                    hover:bg-red-300
                    ">
                        Create

                    </button>

                </div>

            </form>
        </div>
    </div>

</body>