<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

    <title>To-Do List</title>
</head>

<body class="m-20">
    <h1 class="flex justify-center items-center mb-4 mt-8 text-4xl font-extrabold leading-none tracking-tight 
text-gray-800 md:text-5xl lg:text-6xl dark:text-white">Task searched</h1>

    

    <!-- boton volver-->
    <div class="m-2 py-4 flex flex-wrap flex-grow justify-end w-full">
        <div class="flex content-end p-8">
            <a href="<?php echo WEB_ROOT; ?>" class="inline-block px-8 mr-28 py-2 border border-transparent text-sm leading-5 font-medium 
                        rounded-md text-white bg-green-600 hover:bg-green-400 focus:outline-none focus:shadow-outline">
                Go Back to List
            </a>
        </div>
    </div>
    <!-- tabla datos -->
    <table class="min-w-full divide-y divide-gray-200">
        <thead>
            <tr>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Task
                    Number
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Description
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Author
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Creation
                    Date
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Deadline
                </th>
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Last Edited
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Action
                </th>
            </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
            <?php if ($this->task != null): ?>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <?php echo htmlspecialchars($this->task['id']); ?>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <?php echo htmlspecialchars($this->task['description']); ?>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <?php echo htmlspecialchars($this->task['author']); ?>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <span
                                class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full 
                                <?php echo ($this->task['status'] === 'finalized') ? 'bg-green-100 text-green-800' : (($this->task['status'] === 'in process') ? 'bg-yellow-100 text-yellow-800' : 'bg-red-100 text-red-800'); ?>">
                                <?php echo $this->task['status']; ?>
                            </span>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <?php echo $this->task['creationDate']; ?>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <?php echo $this->task['deadline']; ?>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <?php echo $this->task['lastEdited']; ?>
                        </td>
                        <td class=" py-4 whitespace-nowrap">
                            <!-- pasa info del id a través de la URL-->
                            <a href="updateTask?id=<?php echo $this->task['id']; ?>"
                                class="inline-block px-4 py-2 font-medium text-white bg-red-300 rounded-md hover:bg-red-200 focus:outline-none focus:shadow-outline-blue active:bg-red-200 transition duration-150 ease-in-out">
                                Edit
                            </a>
                            <!-- pasa info del id a través del modal-->
                            <button class="ml-2 px-4 py-2 font-medium text-white bg-red-600 rounded-md hover:bg-red-500 
                                    focus:outline-none focus:shadow-outline-red active:bg-red-600 
                                    transition duration-150 ease-in-out"
                                onclick="showDialog('<?php echo $this->task['id']; ?>')">Delete</button>

                            <!-- diseño Pop Up Modal Tailwind -->
                            <div id="dialog_<?php echo $this->task['id']; ?>"
                                class="fixed left-0 top-0 bg-black opacity-0 hidden w-screen h-screen transition-opacity duration-500"
                                onclick="hideDialog(<?php echo $this->task['id']; ?>)">
                                <div class="flex items-center justify-center h-full">
                                    <div class="bg-white rounded shadow-md p-8 mx-auto my-20 md:w-1/2 lg:w-1/3 xl:w-1/4">
                                        <div class="flex items-center gap-5">
                                            <div
                                                class="bg-red-200 rounded-full p-5 text-red-500 flex items-center justify-center w-10 h-10">
                                                <i class="fa-solid fa-exclamation"></i>

                                            </div>
                                            <div>
                                                <h1 class="font-bold text-lg mb-2">Delete Task
                                                    <?php echo $this->task['id'] ?>
                                                </h1>
                                                <p class="whitespace-pre-line">Are you sure you want to delete this task? All
                                                    data wil be lost and cannot be undone.
                                                </p>
                                            </div>
                                        </div>
                                        <div class="flex justify-end gap-4 mt-5">
                                            <button
                                                class="bg-gray-100 border border-gray-300 px-6 py-2 rounded text-black hover:bg-gray-200"
                                                onclick="hideDialog()">Cancel</button>
                                            <a class="bg-red-500 px-6 py-2 rounded text-white hover:bg-red-600"
                                                href="deleteTask?id=<?php echo $this->task['id']; ?>"><button>Delete</button>
                                            </a>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>

                    </tr>
            <?php else: ?>
                <tr>
                    <td colspan="7" class="px-6 py-4 whitespace-no-wrap text-center border-b border-gray-200">
                        <p class="text-red-600">Task <?php echo $this->task['id'];?> not found</p>

                    </td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>


    <!-- funcionamiento Modal-->
    <script>
        function showDialog(taskId) {

            let dialog = document.getElementById(`dialog_${taskId}`);
            dialog.classList.remove('hidden');
            setTimeout(() => {
                dialog.classList.remove('opacity-0');
            }, 20);
        }

        function hideDialog(taskId) {

            let dialog = document.getElementById(`dialog_${taskId}`);
            dialog.classList.add('opacity-0');
            setTimeout(() => {
                dialog.classList.add('hidden');
            }, 500);
            event.stopPropagation();
        }
    </script>
</body>

</html>







<!--crear modal con tailwind: https://www.youtube.com/watch?v=7KmXhRJuEi8-->